### ISSUE TITLE
Thoughts around expiring invitations after N. 

### ISSUE THREAD

**Issue by joshchernoff** [pow-auth/pow#327]
I think invitations should expire by default since while very unlikely under most circumstance could be used as a vector to sign up as an imposter given the attacker uses brute force to guess a invite token. Which given the current design could allow them unlimited time to guess. 

My first thought was to make a guide around how to manage this yourself via a background job that looks for users who has a invitation_accepted_at of null but has a invitation_token and a inserted_at date grater than N. 

While this maybe a good first step, I think it maybe worth making this a default of the system given people may over look this attack vector. 

Thoughts?

**Comment by danschultzer** [comment]
Yeah, I see the issue, though with the UUIDv4 token it'll be extremely unlikely somebody wants to brute force that.

The best approach would probably be to generate a new token if the previous token is expired, and send out an e-mail with the new token. An easy way that won't break what already exists would be to use a second token that's stored in the cache store with a TTL. So the user can be fetched by the `invitation_token`, but you would also need a valid ticket to accept the invitation. This would be akin to password reset.

**Comment by joshchernoff** [comment]
Nice idea.
